# Generated by Django 3.0.6 on 2020-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='totalEnc',
            field=models.BigIntegerField(default=0, verbose_name='Total Encuestas'),
        ),
    ]
