# Generated by Django 3.0.6 on 2020-05-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0002_resumen_totalenc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre y Apellidos')),
                ('address', models.TextField(max_length=250, verbose_name='Direccón')),
                ('incidencia', models.TextField(max_length=500, verbose_name='Incidencias')),
                ('isResolve', models.BooleanField(default=False, help_text='Si esta marcada/(True) esta resuelta la incidencia', verbose_name='Resuelta')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias_information',
                'ordering': ['id'],
            },
        ),
    ]
