# Generated by Django 3.0.6 on 2020-05-23 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0007_auto_20200523_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapStudentApp.Zona', verbose_name='zona'),
        ),
    ]
