# Generated by Django 3.0.6 on 2020-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0008_auto_20200523_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True, verbose_name='Nombre y Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True, verbose_name='Nombre y Apellidos'),
            preserve_default=False,
        ),
    ]
