# Generated by Django 3.0.6 on 2020-05-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0011_auto_20200525_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha del Reporte'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapStudentApp.Zona', verbose_name='zona'),
        ),
    ]
