# Generated by Django 3.0.6 on 2020-05-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0014_auto_20200525_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
