# Generated by Django 3.0.6 on 2020-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0015_zona_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='coordinador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre(s) y Apellido(s) del coordinador'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre Zona'),
        ),
    ]
