# Generated by Django 3.0.6 on 2020-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0018_auto_20200525_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha del Reporte'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
