# Generated by Django 3.0.6 on 2020-05-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0020_auto_20200526_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='address',
            field=models.TextField(max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='moduloGobNo',
            field=models.BigIntegerField(default=False, verbose_name='Módulo de Gobierno/Total No'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='moduloGobSi',
            field=models.BigIntegerField(default=True, verbose_name='Módulo de Gobierno/Total Si'),
        ),
    ]
