# Generated by Django 3.0.6 on 2020-05-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0021_auto_20200526_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Reporte'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='atetionNo',
            field=models.BigIntegerField(verbose_name='Atención de Familia/Total No'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='atetionYes',
            field=models.BigIntegerField(verbose_name='Atención de Familia/Total Si'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
