# Generated by Django 3.0.6 on 2020-05-30 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0023_auto_20200527_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='isResolve',
            field=models.BooleanField(default=False, verbose_name='Resuelta'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Reporte'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
