# Generated by Django 3.0.6 on 2020-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0024_auto_20200530_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='name',
            field=models.CharField(max_length=150, unique_for_date='startDate', verbose_name='Nombre Zona'),
        ),
    ]
