# Generated by Django 3.0.6 on 2020-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapStudentApp', '0025_auto_20200530_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre Zona'),
        ),
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('name', 'startDate')},
        ),
    ]
